concelhos:concelhos.o funcoes.o
	gcc -Wall concelhos.o funcoes.o -o concelhos

concelhos.o:concelhos.c
	gcc -Wall -c concelhos.c -o concelhos.o

funcoes.o:funcoes.o
	gcc -Wall -c funcoes.c -o funcoes.o